version: "3.9"
services:
    promod-mysql:
        image: mysql
        container_name: promod-mysql
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=promod
        volumes:
            - ./promod-mysql/${SQL_FILE}:/docker-entrypoint-initdb.d/init.sql:ro
            - ${DB_DATA_FOLDER}:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", 'mysqladmin ping']
            interval: 10s
            timeout: 2s
            retries: 10
        ports:
            - ${DB_EXPOSE_PORT}:3306
            

    promod-spring:
        build: ./promod-spring
        container_name: promod-spring
        depends_on:
            promod-mysql:
               condition: service_healthy
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://promod-mysql:3306/promod?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Europe/Prague
            - SPRING_DATASOURCE_USERNAME=${DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - PROMOD_CORS_ALLOWED-ORIGINS=http://localhost:${WEB_APP_EXPOSE_PORT}/
        ports:
            - ${SPRING_EXPOSE_PORT}:8080
            
    promod-react:
        build: ./promod-react
        container_name: promod-react
        depends_on:
            - promod-spring
        environment:
            serverURL:
                http://localhost:${SPRING_EXPOSE_PORT}/
        ports:
            - ${WEB_APP_EXPOSE_PORT}:80
